#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jxc?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#    mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.nvd.bean classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml


#  分页助手
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 80
  servlet:
    context-path: /